### PR TITLE
Russian adaptations for dev branch

### PR DESCRIPTION
**Pull request by r72cccp**
### BonsaiERP russian adaptation 
* some translations added
* some bugs fixed to run with empty database

### CODE REVIEW

**Comment by boriscy** [comment]
Wow great job you inspire me to help, I will start translating. Do you know a free service to translate for open source apps like https://www.localeapp.com/

**Comment by r72cccp** [comment]
Great app, but it isn't working :(

**Comment by boriscy** [comment]
I will work on making installation easy, thanks

**Comment by r72cccp** [comment]
May be screencast is a better way to get some process understanding with localeapp installation?

**Pull request merged**
